// KIRO-AI: Panel de recommandations IA avec actions concrètes
// Affiche les suggestions du LLM de manière structurée et actionnable
function AIRecommendationsPanel({ recommendations }) {

  if (!recommendations || recommendations.length === 0) {
    return null;
  }

  // KIRO-AI: Copier les recommandations en Markdown
  const copyAsMarkdown = () => {
    const markdown = `# 💡 AutoUX Recommendations\n\n${recommendations
      .map((rec, i) => `## ${i + 1}. ${rec.summary}\n\n**Why?** ${rec.rationale}\n\n**References:** ${rec.references?.join(', ') || 'N/A'}\n`)
      .join('\n')}`;
    
    navigator.clipboard.writeText(markdown);
    alert('✅ Recommendations copied as Markdown!');
  };

  // KIRO-AI: Copier en JSON
  const copyAsJSON = () => {
    navigator.clipboard.writeText(JSON.stringify(recommendations, null, 2));
    alert('✅ Recommendations copied as JSON!');
  };

  return (
    <div
      style={{
        padding: '24px',
        backgroundColor: 'white',
        borderRadius: '12px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
        marginBottom: '24px',
        border: '2px solid #6b4eff',
      }}
    >
      {/* KIRO-AI: En-tête avec badge IA */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div
            style={{
              fontSize: '2em',
              background: 'linear-gradient(135deg, #6b4eff 0%, #0073bb 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            🤖
          </div>
          <div>
            <h3 style={{ margin: '0 0 4px 0', fontSize: '1.3em', color: '#111827', fontWeight: '700' }}>
              💡 AutoUX Recommends
            </h3>
            <p style={{ margin: 0, fontSize: '0.85em', color: '#666' }}>
              Priority actions generated by AI
            </p>
          </div>
        </div>

        {/* KIRO-AI: Boutons de copie */}
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            onClick={copyAsMarkdown}
            style={{
              padding: '8px 16px',
              backgroundColor: '#f3f4f6',
              color: '#374151',
              border: '1px solid #d1d5db',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '0.85em',
              fontWeight: '500',
              transition: 'all 0.2s ease',
            }}
            onMouseOver={(e) => {
              e.target.style.backgroundColor = '#e5e7eb';
            }}
            onMouseOut={(e) => {
              e.target.style.backgroundColor = '#f3f4f6';
            }}
          >
            📋 Markdown
          </button>
          <button
            onClick={copyAsJSON}
            style={{
              padding: '8px 16px',
              backgroundColor: '#f3f4f6',
              color: '#374151',
              border: '1px solid #d1d5db',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '0.85em',
              fontWeight: '500',
              transition: 'all 0.2s ease',
            }}
            onMouseOver={(e) => {
              e.target.style.backgroundColor = '#e5e7eb';
            }}
            onMouseOut={(e) => {
              e.target.style.backgroundColor = '#f3f4f6';
            }}
          >
            {} JSON
          </button>
        </div>
      </div>

      {/* KIRO-AI: Liste des recommandations */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        {recommendations.map((rec, index) => (
          <div
            key={index}
            style={{
              padding: '16px',
              backgroundColor: '#f9fafb',
              borderRadius: '8px',
              borderLeft: '4px solid #6b4eff',
              transition: 'all 0.2s ease',
            }}
            onMouseOver={(e) => {
              e.currentTarget.style.backgroundColor = '#f3f4f6';
              e.currentTarget.style.transform = 'translateX(4px)';
            }}
            onMouseOut={(e) => {
              e.currentTarget.style.backgroundColor = '#f9fafb';
              e.currentTarget.style.transform = 'translateX(0)';
            }}
          >
            {/* Numéro et titre */}
            <div style={{ display: 'flex', alignItems: 'start', gap: '12px', marginBottom: '8px' }}>
              <div
                style={{
                  minWidth: '28px',
                  height: '28px',
                  backgroundColor: '#6b4eff',
                  color: 'white',
                  borderRadius: '50%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: '0.9em',
                  fontWeight: '700',
                }}
              >
                {index + 1}
              </div>
              <div style={{ flex: 1 }}>
                <h4 style={{ margin: '0 0 8px 0', fontSize: '1.05em', color: '#111827', fontWeight: '600' }}>
                  {rec.summary}
                </h4>
                <p style={{ margin: '0 0 8px 0', fontSize: '0.9em', color: '#666', lineHeight: '1.5' }}>
                  <strong>Why?</strong> {rec.rationale}
                </p>
                {rec.references && rec.references.length > 0 && (
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                    {rec.references.map((ref, i) => (
                      <span
                        key={i}
                        style={{
                          padding: '4px 10px',
                          backgroundColor: 'white',
                          border: '1px solid #d1d5db',
                          borderRadius: '4px',
                          fontSize: '0.75em',
                          color: '#6b7280',
                          fontWeight: '500',
                        }}
                      >
                        📚 {ref}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default AIRecommendationsPanel;
