// KIRO-AI: Report download button with multiple options
// Allows downloading as JSON or copying as Markdown
function DownloadReportButton({ report }) {
  const [showMenu, setShowMenu] = useState(false);

  if (!report) return null;

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `autoux-report-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShowMenu(false);
  };

  const copyMarkdown = () => {
    const markdown = `# 📊 AutoUX Report - ${new Date().toLocaleDateString('en-US')}

## Summary
${report.summary}

## Statistics
- **Total Issues:** ${report.stats?.total || 0}
- **Critical:** ${report.stats?.bySeverity?.high || 0}
- **Medium:** ${report.stats?.bySeverity?.medium || 0}
- **Minor:** ${report.stats?.bySeverity?.low || 0}

## Detected Issues
${(report.topIssues || report.issues || []).map((issue, i) => `
### ${i + 1}. ${issue.description}
- **Type:** ${issue.type}
- **Severity:** ${issue.severity}
- **Timestamp:** ${issue.timestamp}
`).join('\n')}

## Recommendations
${(report.recommendations || []).map((rec, i) => `
### ${i + 1}. ${rec.summary}
**Why?** ${rec.rationale}
**References:** ${rec.references?.join(', ') || 'N/A'}
`).join('\n')}

---
*Generated by AutoUX - AI-Powered UX Analysis*
`;
    
    navigator.clipboard.writeText(markdown);
    alert('✅ Report copied as Markdown!');
    setShowMenu(false);
  };

  return (
    <div style={{ position: 'relative', display: 'inline-block' }}>
      <button
        onClick={() => setShowMenu(!showMenu)}
        style={{
          padding: '12px 24px',
          background: 'linear-gradient(135deg, #6b4eff 0%, #0073bb 100%)',
          color: 'white',
          border: 'none',
          borderRadius: '8px',
          cursor: 'pointer',
          fontSize: '0.95em',
          fontWeight: '600',
          transition: 'all 0.3s ease',
          boxShadow: '0 2px 8px rgba(107, 78, 255, 0.3)',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
        }}
        onMouseOver={(e) => {
          e.target.style.transform = 'translateY(-2px)';
          e.target.style.boxShadow = '0 4px 12px rgba(107, 78, 255, 0.4)';
        }}
        onMouseOut={(e) => {
          e.target.style.transform = 'translateY(0)';
          e.target.style.boxShadow = '0 2px 8px rgba(107, 78, 255, 0.3)';
        }}
      >
        <span>📥</span>
        <span>Download Report</span>
        <span style={{ fontSize: '0.8em' }}>▼</span>
      </button>

      {showMenu && (
        <div
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            marginTop: '8px',
            backgroundColor: 'white',
            border: '1px solid #e5e7eb',
            borderRadius: '8px',
            boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
            zIndex: 1000,
            minWidth: '200px',
            overflow: 'hidden',
          }}
        >
          <button
            onClick={downloadJSON}
            style={{
              width: '100%',
              padding: '12px 16px',
              border: 'none',
              backgroundColor: 'white',
              cursor: 'pointer',
              textAlign: 'left',
              fontSize: '0.9em',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              transition: 'background-color 0.2s ease',
            }}
            onMouseOver={(e) => {
              e.target.style.backgroundColor = '#f3f4f6';
            }}
            onMouseOut={(e) => {
              e.target.style.backgroundColor = 'white';
            }}
          >
            <span>{}</span>
            <span>Download JSON</span>
          </button>
          <button
            onClick={copyMarkdown}
            style={{
              width: '100%',
              padding: '12px 16px',
              border: 'none',
              backgroundColor: 'white',
              cursor: 'pointer',
              textAlign: 'left',
              fontSize: '0.9em',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              transition: 'background-color 0.2s ease',
            }}
            onMouseOver={(e) => {
              e.target.style.backgroundColor = '#f3f4f6';
            }}
            onMouseOut={(e) => {
              e.target.style.backgroundColor = 'white';
            }}
          >
            <span>📋</span>
            <span>Copy Markdown</span>
          </button>
        </div>
      )}

      {/* Fermer le menu si on clique ailleurs */}
      {showMenu && (
        <div
          onClick={() => setShowMenu(false)}
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            zIndex: 999,
          }}
        />
      )}
    </div>
  );
}

// Import manquant
import { useState } from 'react';

export default DownloadReportButton;
