import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import Recommendations from '../Recommendations.jsx';

describe('Recommendations Component', () => {
  const mockRecommendations = [
    {
      priority: 1,
      title: 'Optimize API Response Times',
      description: 'Reduce server response time to under 2.5s for better LCP',
      why: 'Slow API responses directly impact Largest Contentful Paint (LCP), a core Web Vital that affects user experience and SEO rankings.',
      references: ['LCP', 'WCAG 1.4.3'],
      codeExample: 'const optimized = await cache.get(key);',
    },
    {
      priority: 2,
      title: 'Add Alt Text to Images',
      description: 'All images must have descriptive alt attributes',
      why: 'Screen readers rely on alt text to describe images to visually impaired users.',
      references: ['WCAG 1.1.1', '4.1.2'],
    },
    {
      priority: 3,
      title: 'Improve Keyboard Navigation',
      description: 'Ensure all interactive elements are keyboard accessible',
      why: 'Many users rely on keyboard navigation for accessibility.',
      references: ['WCAG 2.1.1'],
    },
  ];

  const mockMarkdown = '# Recommendations\n\n## 1. Optimize API Response Times\n\nReduce server response time...';

  beforeEach(() => {
    // Mock clipboard API
    Object.assign(navigator, {
      clipboard: {
        writeText: vi.fn().mockResolvedValue(undefined),
      },
    });
  });

  it('should render recommendations header with AI icon', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    expect(screen.getByText('💡 AutoUX Recommends')).toBeInTheDocument();
    expect(screen.getByText('Priority actions generated by AI')).toBeInTheDocument(
);
  });

  it('should render tab switcher with Visual, Markdown, and JSON tabs', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    expect(screen.getByRole('tab', { name: /visual/i })).toBeInTheDocument();
    expect(screen.getByRole('tab', { name: /markdown/i })).toBeInTheDocument();
    expect(screen.getByRole('tab', { name: /json/i })).toBeInTheDocument();
  });

  it('should display prioritized list in visual view', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    expect(screen.getByText('Optimize API Response Times')).toBeInTheDocument();
    expect(screen.getByText('Add Alt Text to Images')).toBeInTheDocument();
    expect(screen.getByText('Improve Keyboard Navigation')).toBeInTheDocument();
  });

  it('should expand and collapse recommendation sections', async () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    // First item should be expanded by default
    expect(screen.getByText(/Slow API responses directly impact/i)).toBeInTheDocument();
    
    // Click to collapse
    const firstButton = screen.getByText('Optimize API Response Times').closest('button');
    fireEvent.click(firstButton);
    
    await waitFor(() => {
      expect(screen.queryByText(/Slow API responses directly impact/i)).not.toBeInTheDocument();
    });
  });

  it('should display WCAG references as clickable links', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    // WCAG links should be present
    const wcagLinks = screen.getAllByText(/WCAG/i);
    expect(wcagLinks.length).toBeGreaterThan(0);
    
    // Check that links have correct href
    const wcagLink = screen.getByText('WCAG 1.4.3');
    expect(wcagLink).toHaveAttribute('href', 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum');
    expect(wcagLink).toHaveAttribute('target', '_blank');
  });

  it('should display Web Vitals references as clickable links', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    // Web Vitals links should be present
    const lcpLink = screen.getByText(/⚡ LCP/i);
    expect(lcpLink).toHaveAttribute('href', 'https://web.dev/lcp/');
    expect(lcpLink).toHaveAttribute('target', '_blank');
  });

  it('should display "Why this matters" explanation', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    expect(screen.getByText(/💡 Why this matters:/i)).toBeInTheDocument();
    expect(screen.getByText(/Slow API responses directly impact/i)).toBeInTheDocument();
  });

  it('should display code examples with copy button', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    expect(screen.getByText(/const optimized = await cache.get/i)).toBeInTheDocument();
    expect(screen.getByLabelText('Copy code example')).toBeInTheDocument();
  });

  it('should copy code example to clipboard', async () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const copyButton = screen.getByLabelText('Copy code example');
    fireEvent.click(copyButton);
    
    await waitFor(() => {
      expect(navigator.clipboard.writeText).toHaveBeenCalledWith('const optimized = await cache.get(key);');
    });
    
    expect(screen.getByText('✓ Copied')).toBeInTheDocument();
  });

  it('should switch to Markdown view', async () => {
    render(<Recommendations recommendations={mockRecommendations} markdown={mockMarkdown} />);
    
    const markdownTab = screen.getByRole('tab', { name: /markdown/i });
    fireEvent.click(markdownTab);
    
    // Wait for animation to complete
    await waitFor(() => {
      expect(screen.getByText('📋 Copy Markdown')).toBeInTheDocument();
    });
  });

  it('should switch to JSON view', async () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const jsonTab = screen.getByRole('tab', { name: /json/i });
    fireEvent.click(jsonTab);
    
    // Wait for animation to complete
    await waitFor(() => {
      expect(screen.getByText('📋 Copy JSON')).toBeInTheDocument();
    });
    // JSON content should be visible
    expect(screen.getByText(/"priority": 1/i)).toBeInTheDocument();
  });

  it('should copy Markdown to clipboard', async () => {
    render(<Recommendations recommendations={mockRecommendations} markdown={mockMarkdown} />);
    
    const markdownTab = screen.getByRole('tab', { name: /markdown/i });
    fireEvent.click(markdownTab);
    
    // Wait for animation and button to appear
    const copyButton = await screen.findByText('📋 Copy Markdown');
    fireEvent.click(copyButton);
    
    await waitFor(() => {
      expect(navigator.clipboard.writeText).toHaveBeenCalledWith(mockMarkdown);
    });
  });

  it('should copy JSON to clipboard', async () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const jsonTab = screen.getByRole('tab', { name: /json/i });
    fireEvent.click(jsonTab);
    
    // Wait for animation and button to appear
    const copyButton = await screen.findByText('📋 Copy JSON');
    fireEvent.click(copyButton);
    
    await waitFor(() => {
      expect(navigator.clipboard.writeText).toHaveBeenCalledWith(
        JSON.stringify(mockRecommendations, null, 2)
      );
    });
  });

  it('should support keyboard navigation between tabs', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const visualTab = screen.getByRole('tab', { name: /visual/i });
    const markdownTab = screen.getByRole('tab', { name: /markdown/i });
    const jsonTab = screen.getByRole('tab', { name: /json/i });
    
    // Initially visual tab should be selected
    expect(visualTab).toHaveAttribute('aria-selected', 'true');
    expect(markdownTab).toHaveAttribute('aria-selected', 'false');
    
    // Keyboard navigation handlers are present
    expect(visualTab).toHaveAttribute('aria-controls', 'recommendations-panel');
    expect(markdownTab).toHaveAttribute('aria-controls', 'recommendations-panel');
    expect(jsonTab).toHaveAttribute('aria-controls', 'recommendations-panel');
  });

  it('should handle empty recommendations gracefully', () => {
    const { container } = render(<Recommendations recommendations={[]} />);
    
    expect(container.firstChild).toBeNull();
  });

  it('should handle missing optional fields', () => {
    const minimalRecommendations = [
      {
        title: 'Basic Recommendation',
      },
    ];
    
    render(<Recommendations recommendations={minimalRecommendations} />);
    
    expect(screen.getByText('Basic Recommendation')).toBeInTheDocument();
  });

  it('should display priority badges with correct colors', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    // Priority 1 should be red, 2 should be amber, 3+ should be purple
    const priorityBadges = screen.getAllByText(/^[1-3]$/);
    expect(priorityBadges).toHaveLength(3);
  });

  it('should be keyboard accessible for expand/collapse', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const firstButton = screen.getByText('Optimize API Response Times').closest('button');
    
    // Should support Enter key
    fireEvent.keyDown(firstButton, { key: 'Enter' });
    expect(firstButton).toHaveAttribute('aria-expanded');
    
    // Should support Space key
    fireEvent.keyDown(firstButton, { key: ' ' });
    expect(firstButton).toHaveAttribute('aria-expanded');
  });

  it('should have proper ARIA attributes', () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const tablist = screen.getByRole('tablist');
    expect(tablist).toBeInTheDocument();
    
    const tabs = screen.getAllByRole('tab');
    tabs.forEach(tab => {
      expect(tab).toHaveAttribute('aria-selected');
      expect(tab).toHaveAttribute('aria-controls');
    });
    
    const tabpanel = screen.getByRole('tabpanel');
    expect(tabpanel).toBeInTheDocument();
  });

  it('should animate tab transitions', async () => {
    render(<Recommendations recommendations={mockRecommendations} />);
    
    const markdownTab = screen.getByRole('tab', { name: /markdown/i });
    fireEvent.click(markdownTab);
    
    // AnimatePresence should handle the transition
    await waitFor(() => {
      expect(screen.getByLabelText('Copy as Markdown')).toBeInTheDocument();
    });
  });
});
